package org.talend.designer.codegen.translators.internet.scp;

import org.talend.core.model.process.INode;
import org.talend.core.model.process.ElementParameterParser;
import org.talend.designer.codegen.config.CodeGeneratorArgument;
import java.util.List;
import java.util.Map;

public class TSCPGetMainJava
{
  protected static String nl;
  public static synchronized TSCPGetMainJava create(String lineSeparator)
  {
    nl = lineSeparator;
    TSCPGetMainJava result = new TSCPGetMainJava();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "";
  protected final String TEXT_2 = NL + NL + "        String[] sourceFileNames_";
  protected final String TEXT_3 = " = new String[]{";
  protected final String TEXT_4 = NL + "\t\t\t\t";
  protected final String TEXT_5 = ",";
  protected final String TEXT_6 = NL + "\t\t};" + NL + "\t\t" + NL + "java.io.File dir_";
  protected final String TEXT_7 = " = null;" + NL + "try{";
  protected final String TEXT_8 = NL + "\tfor (String sourceFile_";
  protected final String TEXT_9 = " : sourceFileNames_";
  protected final String TEXT_10 = ") {" + NL + "\t\tif (sourceFile_";
  protected final String TEXT_11 = " != null&& sourceFile_";
  protected final String TEXT_12 = ".length() != 0) {" + NL + "\t\t\tsourceFile_";
  protected final String TEXT_13 = " = \"\\\"\" + sourceFile_";
  protected final String TEXT_14 = " + \"\\\"\";" + NL + "\t\t\tsourceFile_";
  protected final String TEXT_15 = "=sourceFile_";
  protected final String TEXT_16 = ".replaceAll(\"\\\\\\\\\",\"/\"); " + NL + "\t\t\tint index_";
  protected final String TEXT_17 = "=sourceFile_";
  protected final String TEXT_18 = ".lastIndexOf(\"/\");" + NL + "\t\t\tif(index_";
  protected final String TEXT_19 = " >0){" + NL + "\t\t\t\tdir_";
  protected final String TEXT_20 = " = new java.io.File(";
  protected final String TEXT_21 = ");" + NL + "\t\t\t\tString extension_";
  protected final String TEXT_22 = "=\tsourceFile_";
  protected final String TEXT_23 = ".substring(index_";
  protected final String TEXT_24 = ",sourceFile_";
  protected final String TEXT_25 = ".length()-1);" + NL + "\t\t\t\tjava.io.File file_";
  protected final String TEXT_26 = " = new java.io.File(dir_";
  protected final String TEXT_27 = ", extension_";
  protected final String TEXT_28 = ");" + NL + "\t\t\t\tif(!file_";
  protected final String TEXT_29 = ".exists()){" + NL + "\t\t\t\t  file_";
  protected final String TEXT_30 = ".getParentFile().mkdirs();" + NL + "\t\t\t\t}" + NL + "\t\t\t\tjava.io.FileOutputStream out_";
  protected final String TEXT_31 = " = null;" + NL + "\t\t\t\t" + NL + "\t\t\t\t//copy action" + NL + "\t\t\t\tjava.io.InputStream is_";
  protected final String TEXT_32 = " = null;" + NL + "\t\t\t\tbyte[] buffer_";
  protected final String TEXT_33 = " = new byte[8192];" + NL + "\t\t\t\tint receive_";
  protected final String TEXT_34 = " = -1;" + NL + "\t\t\t\ttry {" + NL + "\t\t\t\t\tout_";
  protected final String TEXT_35 = " = new java.io.FileOutputStream(file_";
  protected final String TEXT_36 = ", true);" + NL + "\t\t\t\t\tis_";
  protected final String TEXT_37 = " = scp_";
  protected final String TEXT_38 = ".get(sourceFile_";
  protected final String TEXT_39 = ");" + NL + "\t\t\t\t\t" + NL + "    \t\t\t\twhile((receive_";
  protected final String TEXT_40 = " = is_";
  protected final String TEXT_41 = ".read(buffer_";
  protected final String TEXT_42 = "))!=-1) {" + NL + "    \t\t\t\t\tout_";
  protected final String TEXT_43 = ".write(buffer_";
  protected final String TEXT_44 = ", 0, receive_";
  protected final String TEXT_45 = ");" + NL + "    \t\t\t\t}" + NL + "\t\t\t\t} catch(java.lang.Exception e_";
  protected final String TEXT_46 = ") {" + NL + "                \tif(out_";
  protected final String TEXT_47 = " != null){" + NL + "                \t\tout_";
  protected final String TEXT_48 = ".close();" + NL + "                \t}" + NL + "\t\t\t\t\t//only delete empty file when exception happen?this is old action,we keep it." + NL + "            \t\tif(file_";
  protected final String TEXT_49 = ".length() == 0){" + NL + "            \t\t\tfile_";
  protected final String TEXT_50 = ".delete();" + NL + "            \t\t}" + NL + "            \t\tthrow e_";
  protected final String TEXT_51 = ";" + NL + "\t\t\t\t} finally {" + NL + "                \tif(out_";
  protected final String TEXT_52 = " != null){" + NL + "                \t\tout_";
  protected final String TEXT_53 = ".close();" + NL + "                \t}" + NL + "                \t" + NL + "                \tif(is_";
  protected final String TEXT_54 = " != null) {" + NL + "                \t\tis_";
  protected final String TEXT_55 = ".close();" + NL + "                \t}" + NL + "\t\t\t\t}" + NL + "\t\t\t\t" + NL + "\t\t\t\tnb_file_";
  protected final String TEXT_56 = " ++ ;" + NL + "\t\t\t\t";
  protected final String TEXT_57 = NL + "\t\t\t\t\tlog.debug(\"";
  protected final String TEXT_58 = " - Downloaded file \" + nb_file_";
  protected final String TEXT_59 = " +  \": \" + sourceFile_";
  protected final String TEXT_60 = " + \" successfully.\");" + NL + "\t\t\t\t";
  protected final String TEXT_61 = NL + "\t\t\t}" + NL + "\t\t}" + NL + "\t}" + NL + "\tif(nb_file_";
  protected final String TEXT_62 = ">0){" + NL + "\t\tglobalMap.put(\"";
  protected final String TEXT_63 = "_STATUS\", \"File get OK.\");" + NL + "\t}else{" + NL + "\t\tglobalMap.put(\"";
  protected final String TEXT_64 = "_STATUS\", \"No file transfered.\");" + NL + "\t}";
  protected final String TEXT_65 = "        " + NL + "        String parentPath_";
  protected final String TEXT_66 = " = new java.io.File(";
  protected final String TEXT_67 = ").getPath();" + NL + "        java.util.List<String> list_";
  protected final String TEXT_68 = " = new java.util.ArrayList<String>();" + NL + "        for (int i_";
  protected final String TEXT_69 = " = 0; i_";
  protected final String TEXT_70 = " < sourceFileNames_";
  protected final String TEXT_71 = ".length; i_";
  protected final String TEXT_72 = "++) {" + NL + "            String fileName_";
  protected final String TEXT_73 = " = sourceFileNames_";
  protected final String TEXT_74 = "[i_";
  protected final String TEXT_75 = "];" + NL + "            if (!new java.io.File((parentPath_";
  protected final String TEXT_76 = "), (fileName_";
  protected final String TEXT_77 = ")).exists()) {" + NL + "                list_";
  protected final String TEXT_78 = ".add(fileName_";
  protected final String TEXT_79 = ");" + NL + "            }" + NL + "        }" + NL + "        sourceFileNames_";
  protected final String TEXT_80 = " = (String[]) list_";
  protected final String TEXT_81 = ".toArray(new String[0]);";
  protected final String TEXT_82 = NL + "\tif(sourceFileNames_";
  protected final String TEXT_83 = "!=null && sourceFileNames_";
  protected final String TEXT_84 = ".length!=0){" + NL + "\t\tfor (String sourceFile_";
  protected final String TEXT_85 = " : sourceFileNames_";
  protected final String TEXT_86 = ") {" + NL + "\t\t\tif (sourceFile_";
  protected final String TEXT_87 = " != null&& sourceFile_";
  protected final String TEXT_88 = ".length() != 0) {" + NL + "\t\t\t\tsourceFile_";
  protected final String TEXT_89 = " = \"\\\"\" + sourceFile_";
  protected final String TEXT_90 = " + \"\\\"\";" + NL + "\t\t\t\tsourceFile_";
  protected final String TEXT_91 = "=sourceFile_";
  protected final String TEXT_92 = ".replaceAll(\"\\\\\\\\\",\"/\"); " + NL + "\t\t\t    int index_";
  protected final String TEXT_93 = "=sourceFile_";
  protected final String TEXT_94 = ".lastIndexOf(\"/\");" + NL + "\t\t\t    if(index_";
  protected final String TEXT_95 = " >0){" + NL + "\t\t\t\t\tdir_";
  protected final String TEXT_96 = " = new java.io.File(";
  protected final String TEXT_97 = ");" + NL + "\t\t\t\t\tString extension_";
  protected final String TEXT_98 = "=\tsourceFile_";
  protected final String TEXT_99 = ".substring(index_";
  protected final String TEXT_100 = ",sourceFile_";
  protected final String TEXT_101 = ".length()-1);" + NL + "\t\t\t\t\tjava.io.File file_";
  protected final String TEXT_102 = " = new java.io.File(dir_";
  protected final String TEXT_103 = ", extension_";
  protected final String TEXT_104 = ");" + NL + "\t\t\t\t\tif(!file_";
  protected final String TEXT_105 = ".exists()){" + NL + "\t\t\t\t  \t\tfile_";
  protected final String TEXT_106 = ".getParentFile().mkdirs();" + NL + "\t\t\t\t\t}" + NL + "\t\t\t\t\tjava.io.FileOutputStream out_";
  protected final String TEXT_107 = " = null;" + NL + "\t\t\t\t\t" + NL + "    \t\t\t\t//copy action" + NL + "    \t\t\t\tjava.io.InputStream is_";
  protected final String TEXT_108 = " = null;" + NL + "    \t\t\t\tbyte[] buffer_";
  protected final String TEXT_109 = " = new byte[8192];" + NL + "    \t\t\t\tint receive_";
  protected final String TEXT_110 = " = -1;" + NL + "    \t\t\t\ttry {" + NL + "    \t\t\t\t\tout_";
  protected final String TEXT_111 = " = new java.io.FileOutputStream(file_";
  protected final String TEXT_112 = ", false);" + NL + "    \t\t\t\t\tis_";
  protected final String TEXT_113 = " = scp_";
  protected final String TEXT_114 = ".get(sourceFile_";
  protected final String TEXT_115 = ");" + NL + "    \t\t\t\t\t" + NL + "        \t\t\t\twhile((receive_";
  protected final String TEXT_116 = " = is_";
  protected final String TEXT_117 = ".read(buffer_";
  protected final String TEXT_118 = "))!=-1) {" + NL + "        \t\t\t\t\tout_";
  protected final String TEXT_119 = ".write(buffer_";
  protected final String TEXT_120 = ", 0, receive_";
  protected final String TEXT_121 = ");" + NL + "        \t\t\t\t}" + NL + "    \t\t\t\t} catch(java.lang.Exception e_";
  protected final String TEXT_122 = ") {" + NL + "                    \tif(out_";
  protected final String TEXT_123 = " != null){" + NL + "                    \t\tout_";
  protected final String TEXT_124 = ".close();" + NL + "                    \t}" + NL + "    \t\t\t\t\t//only delete empty file when exception happen?this is old action,we keep it." + NL + "                \t\tif(file_";
  protected final String TEXT_125 = ".length() == 0){" + NL + "                \t\t\tfile_";
  protected final String TEXT_126 = ".delete();" + NL + "                \t\t}" + NL + "                \t\tthrow e_";
  protected final String TEXT_127 = ";" + NL + "    \t\t\t\t} finally {" + NL + "                    \tif(out_";
  protected final String TEXT_128 = " != null){" + NL + "                    \t\tout_";
  protected final String TEXT_129 = ".close();" + NL + "                    \t}" + NL + "                    \t" + NL + "                    \tif(is_";
  protected final String TEXT_130 = " != null) {" + NL + "                    \t\tis_";
  protected final String TEXT_131 = ".close();" + NL + "                    \t}" + NL + "    \t\t\t\t}" + NL + "    \t\t\t\t" + NL + "\t\t\t\t\tnb_file_";
  protected final String TEXT_132 = " ++ ;" + NL + "\t\t\t\t\t";
  protected final String TEXT_133 = NL + "\t\t\t\t\t\tlog.debug(\"";
  protected final String TEXT_134 = " - Downloaded file \" + nb_file_";
  protected final String TEXT_135 = " +  \": \" + sourceFile_";
  protected final String TEXT_136 = " + \" successfully.\");" + NL + "\t\t\t\t\t";
  protected final String TEXT_137 = NL + "\t\t\t\t}" + NL + "\t\t\t}" + NL + "\t\t}" + NL + "\t\tif(nb_file_";
  protected final String TEXT_138 = ">0){" + NL + "\t\t\tglobalMap.put(\"";
  protected final String TEXT_139 = "_STATUS\", \"File get OK.\");" + NL + "\t\t}else{" + NL + "\t\t\tglobalMap.put(\"";
  protected final String TEXT_140 = "_STATUS\", \"No file transfered.\");" + NL + "\t\t}" + NL + "\t}" + NL + "        ";
  protected final String TEXT_141 = NL + NL + "}catch(java.lang.Exception e_";
  protected final String TEXT_142 = "){" + NL + "\t\tglobalMap.put(\"";
  protected final String TEXT_143 = "_STATUS\", \"File get fail.\");" + NL + "\t\t";
  protected final String TEXT_144 = NL + "\t\t\tlog.fatal(\"";
  protected final String TEXT_145 = " - \"  + e_";
  protected final String TEXT_146 = ".getMessage());" + NL + "\t\t";
  protected final String TEXT_147 = NL + "\t\tthrow e_";
  protected final String TEXT_148 = ";" + NL + "}";
  protected final String TEXT_149 = NL;

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
    stringBuffer.append(TEXT_1);
    
        CodeGeneratorArgument codeGenArgument = (CodeGeneratorArgument) argument;
        INode node = (INode)codeGenArgument.getArgument();
        String cid = node.getUniqueName();      

        String localdir = ElementParameterParser.getValue(node, "__LOCALDIR__");
        String replaceOption = ElementParameterParser.getValue(node,"__REPLACEOPTION__");
        List<Map<String, String>> filelist = (List<Map<String,String>>)ElementParameterParser.getObjectValue(node,"__FILELIST__");
        boolean isLog4jEnabled = ("true").equals(ElementParameterParser.getValue(node.getProcess(), "__LOG4J_ACTIVATE__"));

    stringBuffer.append(TEXT_2);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_3);
    
			for (Map<String, String> file : filelist) {

    stringBuffer.append(TEXT_4);
    stringBuffer.append(file.get("SOURCE"));
    stringBuffer.append(TEXT_5);
              
            }

    stringBuffer.append(TEXT_6);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_7);
    
if(("append").equals(replaceOption)){
    stringBuffer.append(TEXT_8);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_9);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_10);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_11);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_12);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_13);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_14);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_15);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_16);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_17);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_18);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_19);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_20);
    stringBuffer.append(localdir );
    stringBuffer.append(TEXT_21);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_22);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_23);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_24);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_25);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_26);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_27);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_28);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_29);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_30);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_31);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_32);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_33);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_34);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_35);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_36);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_37);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_38);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_39);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_40);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_41);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_42);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_43);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_44);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_45);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_46);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_47);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_48);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_49);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_50);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_51);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_52);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_53);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_54);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_55);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_56);
    if(isLog4jEnabled){
    stringBuffer.append(TEXT_57);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_58);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_59);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_60);
    }
    stringBuffer.append(TEXT_61);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_62);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_63);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_64);
    
}else{
	if(!("overwrite").equals(replaceOption)) {
    stringBuffer.append(TEXT_65);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_66);
    stringBuffer.append(localdir );
    stringBuffer.append(TEXT_67);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_68);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_69);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_70);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_71);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_72);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_73);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_74);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_75);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_76);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_77);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_78);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_79);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_80);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_81);
    
	}

    stringBuffer.append(TEXT_82);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_83);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_84);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_85);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_86);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_87);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_88);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_89);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_90);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_91);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_92);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_93);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_94);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_95);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_96);
    stringBuffer.append(localdir );
    stringBuffer.append(TEXT_97);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_98);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_99);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_100);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_101);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_102);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_103);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_104);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_105);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_106);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_107);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_108);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_109);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_110);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_111);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_112);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_113);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_114);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_115);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_116);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_117);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_118);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_119);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_120);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_121);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_122);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_123);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_124);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_125);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_126);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_127);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_128);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_129);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_130);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_131);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_132);
    if(isLog4jEnabled){
    stringBuffer.append(TEXT_133);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_134);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_135);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_136);
    }
    stringBuffer.append(TEXT_137);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_138);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_139);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_140);
    
}

    stringBuffer.append(TEXT_141);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_142);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_143);
    if(isLog4jEnabled){
    stringBuffer.append(TEXT_144);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_145);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_146);
    }
    stringBuffer.append(TEXT_147);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_148);
    stringBuffer.append(TEXT_149);
    return stringBuffer.toString();
  }
}
